<a href="https://colab.research.google.com/github/JosephHauser912/Advanced-Data/blob/main/FCC%20Numpy%20Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
b = np.random.rand(1000000)

In [5]:
%timeit sum(b)
%timeit np.sum(b)

102 ms ± 28.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
415 µs ± 61.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
def mySum(G):
  s = 0
  for x in G:
    s+=x
  return s
  

In [7]:
A = np.round(10*np.random.rand(5,4))

In [8]:
A

array([[ 4.,  3.,  5.,  5.],
       [ 9.,  3.,  6.,  3.],
       [ 6.,  6.,  1.,  1.],
       [ 3.,  1.,  9.,  4.],
       [10.,  3.,  8.,  3.]])

In [9]:
A[1,2]

6.0

In [11]:
A[1,:]

array([9., 3., 6., 3.])

In [12]:
A[:,1]

array([3., 3., 6., 1., 3.])

In [13]:
A[1:3,2:4]

array([[6., 3.],
       [1., 1.]])

In [14]:
A.T

array([[ 4.,  9.,  6.,  3., 10.],
       [ 3.,  3.,  6.,  1.,  3.],
       [ 5.,  6.,  1.,  9.,  8.],
       [ 5.,  3.,  1.,  4.,  3.]])

In [15]:
import numpy.linalg as la


la.inv(np.random.rand(3,3))

In [19]:
A.sort(axis=1)
A

array([[ 1.,  1.,  1.,  3.],
       [ 3.,  3.,  4.,  5.],
       [ 3.,  3.,  6.,  6.],
       [ 3.,  4.,  8.,  9.],
       [ 5.,  6.,  9., 10.]])