<a href="https://colab.research.google.com/github/JosephHauser912/Advanced-Data/blob/main/NP_Hstack%2C_Vstack%2C_sort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.arange(100)


In [3]:
B = A[[3,5,6]]

In [5]:
B[0] = -4

In [7]:
A
B

array([-4,  5,  6])

In [9]:
B = A[A<40]
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [13]:
B = A[(A<40) & (A>30)]
B

array([31, 32, 33, 34, 35, 36, 37, 38, 39])

In [18]:
A = np.arange(100)

In [19]:
A


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
A = A+5
A

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109])

In [24]:
A = np.round(10*np.random.rand(2,3))
A


array([[ 9.,  5.,  1.],
       [ 5.,  9., 10.]])

In [25]:
A+3

array([[12.,  8.,  4.],
       [ 8., 12., 13.]])

In [26]:
A+(np.arange(2).reshape(2,1))

array([[ 9.,  5.,  1.],
       [ 6., 10., 11.]])

In [28]:
B = np.round(10*np.random.rand(2,2))

In [29]:
B

array([[5., 5.],
       [2., 7.]])

In [32]:
A

array([[ 9.,  5.,  1.],
       [ 5.,  9., 10.]])

In [31]:
C = np.hstack((A,B))
C

array([[ 9.,  5.,  1.,  5.,  5.],
       [ 5.,  9., 10.,  2.,  7.]])

In [35]:
A = np.random.permutation(np.arange(10))
A


array([1, 4, 3, 7, 8, 9, 2, 5, 6, 0])

In [37]:
A.sort()
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
A.sort()
A = A[::-1]
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
A = np.array(["abc", "Howare you", "u765", "13er"])

In [41]:
A.sort()
A

array(['13er', 'Howare you', 'abc', 'u765'], dtype='<U10')