<a href="https://colab.research.google.com/github/JosephHauser912/Advanced-Data/blob/main/P4DS_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
jeff_salary = [2700,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300,2500,2500]
base_salary = np.array([jeff_salary, nick_salary,tom_salary])
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


In [6]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])
print(bonus)

[[500 400 400]
 [600 300 400]
 [200 500 400]]


In [7]:
salary_bonus = base_salary + bonus
print(type(salary_bonus))
print(salary_bonus)

<class 'numpy.ndarray'>
[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]


In [9]:
print(salary_bonus.max())

3400


In [11]:
print(np.amax(salary_bonus, axis = 0))

[3200 3400 3400]
